Remove requirement of core PHP extensions
lcobucci/jwt pull request #1009
Opened 2023-04-21 09:17 UTC by cedric-anne

Since PHP 7.4, `ext-hash` is part of PHP core and cannot be disabled (see https://www.php.net/manual/en/hash.installation.php).
Since PHP 8.0, `ext-json` is part of PHP core and cannot be disabled (see https://www.php.net/manual/en/json.installation.php).

I think they could be removed from `composer.json` require section.

2023-04-21 09:33 UTC, cedric-anne commented
Lint job would be fixed by https://github.com/maglnet/ComposerRequireChecker/pull/399.

2023-04-21 21:17 UTC, Ocramius commented
* [ ] needs https://github.com/maglnet/ComposerRequireChecker/pull/400

2023-04-22 10:05 UTC, Ocramius requested changes
`composer.lock` needs updating too

2023-04-22 11:36 UTC, Ocramius approved these changes
Thanks @cedric-anne!

2023-07-11 19:24 UTC, closed without merging