Add PlainToken interface to expose claims() API
lcobucci/jwt pull request #616
Opened 2020-12-23 08:34 UTC by Slamdunk

Resolve https://github.com/lcobucci/jwt/pull/186
Resolve https://github.com/lcobucci/jwt/issues/228
Resolve https://github.com/lcobucci/jwt/issues/203
Resolve https://github.com/lcobucci/jwt/pull/552
Resolve https://github.com/lcobucci/jwt/issues/611
Resolve https://github.com/lcobucci/jwt/pull/615

2020-12-23 10:29 UTC, lcobucci requested changes
We also need to change the SignedWith constraint: https://github.com/lcobucci/jwt/blob/4.1.x/src/Validation/Constraint/SignedWith.php#L24

(and possibly need to add the payload method to the this interface as well).

2020-12-23 10:29 UTC, lcobucci commented on src/PlainToken.php
> +interface PlainToken extends Token
I'd call this `UnencryptedToken` in this context.

2020-12-23 10:32 UTC, Slamdunk commented
> (and possibly need to add the payload method to the this interface as well).

I didn't change `SignedWith` because indeed it also requires `payload` and `signature`, two methods only useful within the `SignedWith` context.
Just one last confirmation: do you want me to add the two methods mentioned in the new `UnencryptedToken` interface?

2020-12-23 13:34 UTC, lcobucci commented
> > (and possibly need to add the payload method to the this interface as well).
> 
> I didn't change `SignedWith` because indeed it also requires `payload` and `signature`, two methods only useful within the `SignedWith` context.
> Just one last confirmation: do you want me to add the two methods mentioned in the new `UnencryptedToken` interface?

Yes, please. These are relevant to unencrypted tokens.

2020-12-24 12:25 UTC, lcobucci approved these changes
The only thing we're missing to allow people to make full use of this is to change the builder to use the interface as well... That's a minor BC-break, though. I'll think about it for the next few days. Let's get this merged, though.

@Slamdunk thanks!

2020-12-24 12:27 UTC, lcobucci commented
@Slamdunk would please sign your commits? Otherwise I will rebase your branch on the weekend.

2020-12-24 12:30 UTC, Slamdunk commented
The users don't **need** `\Lcobucci\JWT\Builder::getToken` to get changed, even though of course it would be good in the next major.

Users will sill need `assert($token instanceof UnencryptedToken);` because the place where they need this is after `\Lcobucci\JWT\Parser::parse` call, which should will always return a `\Lcobucci\JWT\Token` in case encrypted token will be implemented, asaict.

> would please sign your commits?

Yeah, sorry, It's weird to me that commits appear unsigned just because the key is expired. I'm waiting my Yubikeys, in the meantime I'm using short-lived keys.

I'll re-sign soon

2021-01-05 21:41 UTC, merged

2021-01-05 21:41 UTC, lcobucci commented
@Slamdunk thanks!